system:
    default:
        fielddefinition_edit_templates:
            -
                template: "IntProgEnhancedRelationListBundle:ContentType:field_types.html.twig"
                priority: 1
        field_templates:
            -
                template: "IntProgEnhancedRelationListBundle::content_fields.html.twig"
                priority: 1
        content_view:
            element_simple_link:
                default:
                    controller: 'EzPlatformAdminUiBundle:ContentView:locationView'
                    template: 'IntProgEnhancedRelationListBundle::simple_link.html.twig'
                    match: true
        fielddefinition_settings_templates:
            - {template: '@IntProgEnhancedRelationList/fielddefinition_settings.html.twig', priority: 0}