services:
    IntProg\EnhancedRelationListBundle\Service\RelationAttributeTransformer:
        arguments:
            - []

    IntProg\EnhancedRelationListBundle\Templating\Twig\Extension\RelationAttributeExtension:
        tags:
            - { name: twig.extension }
